# Generated by Django 3.0.8 on 2020-10-20 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='closing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
