# Generated by Django 3.0.8 on 2020-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201020_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='closing_time',
            field=models.DateTimeField(),
        ),
    ]
