# Generated by Django 3.0.8 on 2020-10-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20201021_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
